import Head from "next/head";
import Lodash from "lodash";

import Image from "next/image";
import styles from "../styles/Home.module.css";

import axios from "axios";
import { SiteAPI } from "../config";

import { getPathById } from "../data/main-menu-app.js";

export default function Home({ leyNormasTipos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>LawsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/ANALEGYS-LOGO-leyes.png" width={250} />

        <p className={styles.description}>
          Para comenzar la consulta elija alguno de los siguientes módulos:
        </p>

        <div className={styles.grid}>
          {leyNormasTipos.map((option, index) => {
            return (
              <a
                key={index}
                href={getPathById(option.COD_TIPO).path}
                className="m-1 p-[24px] text-[#000] bg-[#eaeaea] max-w-[300px] text-[20px] border-[#eaeaea] border-solid border-[1px] hover:text-[#fff] 
          transition duration-500 ease-in-out 
          hover:bg-[#00A4D3] transform 
          hover:-translate-y-1 hover:scale-105"
              >
                <h2>{option.DES_TIPO} &rarr;</h2>
                <p className="mt-4">{option.DESCRIPCION}</p>
              </a>
            );
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Desarrollado por BUSYS International
        </a>
      </footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const leyNormasTipos = await axios.get(`${SiteAPI.leyNormasTipos}`);

  return {
    props: {
      leyNormasTipos: leyNormasTipos.data,
    },
    revalidate: 1,
  };
};
