import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LawsApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/ANALEGYS-LOGO-leyes.png" width={250} />

        <p className={styles.description}>
          Para comenzar la consulta elija alguno de los siguientes módulos:
        </p>

        <div className={styles.grid}>
          <a
            href="/laws"
            className="m-1 p-[24px] text-[#000] bg-[#eaeaea] max-w-[300px] text-[20px] border-[#eaeaea] border-solid border-[1px] hover:text-[#fff] 
            transition duration-500 ease-in-out 
            hover:bg-[#00A4D3] transform 
            hover:-translate-y-1 hover:scale-105"
          >
            <h2>LEYES &rarr;</h2>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
          </a>

          <a
            href="/laws"
            className="m-1 p-[24px] text-[#000] bg-[#eaeaea]  max-w-[300px] text-[20px] border-[#eaeaea] border-solid border-[1px] hover:text-[#fff] 
            transition duration-500 ease-in-out 
            hover:bg-[#00A4D3] transform 
            hover:-translate-y-1 hover:scale-105"
          >
            <h2>REGLAMENTOS &rarr;</h2>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
          </a>

          <a
            href="/laws"
            className="m-1 p-[24px] text-[#000] bg-[#eaeaea]  max-w-[300px] text-[20px] border-[#eaeaea] border-solid border-[1px] hover:text-[#fff] 
            transition duration-500 ease-in-out 
            hover:bg-[#00A4D3] transform 
            hover:-translate-y-1 hover:scale-105"
          >
            <h2>DECRETOS &rarr;</h2>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
          </a>

          <a
            href="/laws"
            className="m-1 p-[24px] text-[#000] bg-[#eaeaea]  max-w-[300px] text-[20px] border-[#eaeaea] border-solid border-[1px] hover:text-[#fff] 
            transition duration-500 ease-in-out 
            hover:bg-[#00A4D3] transform 
            hover:-translate-y-1 hover:scale-105"
          >
            <h2>ACUERDOS &rarr;</h2>
            <p className="mt-4">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="#" target="_blank" rel="noopener noreferrer">
          Desarrollado por BUSYS International
        </a>
      </footer>
    </div>
  );
}
