import React, { useState } from "react";
import { LayoutStyles } from "../components/Layout/LayoutStyles";
import axios from "axios";
import TreeComponent from "./components/Tree/TreeComponent";

import Tree from "react-animated-tree";

import Head from "next/head";
import { SiteAPI } from "../config";

export default function Laws({ leyNormasTipos }) {
  console.log(leyNormasTipos);
  const [showContent, setShowContent] = useState(false);

  const isArray = Array.isArray(leyNormasTipos);
  console.log(isArray);

  let nodes = [];
  if (isArray) {
    nodes = leyNormasTipos;
    console.log("HERE!");
    /*
    nodes = [
      {
        value: leyNormasTipos.COD_NORMA,
        label: leyNormasTipos.DES_DESCRIPCION,
        children: [
          {
            value: "Employee Evaluations.zip",
            label: "Employee Evaluations.zip",
            icon: <i className="far fa-file-archive icon-color" />,
          },
          {
            value: "Expense Report.pdf",
            label: "Expense Report.pdf",
            icon: <i className="far fa-file-pdf icon-color" />,
          },
          {
            value: "notes.txt",
            label: "notes.txt",
            icon: <i className="far fa-file-alt icon-color" />,
          },
        ],
      },
      {
        value: "Photos",
        label: "Photos",
        children: [
          {
            value: "nyan-cat.gif",
            label: "nyan-cat.gif",
            icon: <i className="far fa-file-image icon-color" />,
          },
          {
            value: "SpaceX Falcon9 liftoff.jpg",
            label: "SpaceX Falcon9 liftoff.jpg",
            icon: <i className="far fa-file-image icon-color" />,
          },
        ],
      },
    ];
    */
  } else {
    nodes = [
      {
        value: leyNormasTipos.COD_NORMA,
        label: leyNormasTipos.DES_DESCRIPCION,
        children: [
          {
            value: "Employee Evaluations.zip",
            label: "Employee Evaluations.zip",
            icon: <i className="far fa-file-archive icon-color" />,
            children: [
              {
                value: "A",
                label: "A",
                icon: <i className="far fa-file-archive icon-color" />,
              },
              {
                value: "B",
                label: "B",
                icon: <i className="far fa-file-pdf icon-color" />,
              },
              {
                value: "C",
                label: "C",
                icon: <i className="far fa-file-alt icon-color" />,
              },
            ],
          },
          {
            value: "Expense Report.pdf",
            label: "Expense Report.pdf",
            icon: <i className="far fa-file-pdf icon-color" />,
          },
          {
            value: "notes.txt",
            label: "notes.txt",
            icon: <i className="far fa-file-alt icon-color" />,
          },
        ],
      },
    ];
  }

  /*
  const nodes = [
    {
      value: "Leyes",
      label: "Leyes",
      children: [
        {
          value: "Employee Evaluations.zip",
          label: "Employee Evaluations.zip",
          icon: <i className="far fa-file-archive icon-color" />,
        },
        {
          value: "Expense Report.pdf",
          label: "Expense Report.pdf",
          icon: <i className="far fa-file-pdf icon-color" />,
        },
        {
          value: "notes.txt",
          label: "notes.txt",
          icon: <i className="far fa-file-alt icon-color" />,
        },
      ],
    },
    {
      value: "Photos",
      label: "Photos",
      children: [
        {
          value: "nyan-cat.gif",
          label: "nyan-cat.gif",
          icon: <i className="far fa-file-image icon-color" />,
        },
        {
          value: "SpaceX Falcon9 liftoff.jpg",
          label: "SpaceX Falcon9 liftoff.jpg",
          icon: <i className="far fa-file-image icon-color" />,
        },
      ],
    },
  ];
  */

  return (
    <LayoutStyles>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header tabIndex="0"></header>
      <div id="nav-container">
        <div className="bg"></div>
        <div className="button" tabIndex="0">
          <span className="icon-bar"></span>
          <span className="icon-bar"></span>
          <span className="icon-bar"></span>
        </div>
        <div id="nav-content" tabIndex="0">
          <ul>
            <li>
              <a href="#0">Leyes</a>
            </li>
            <li>
              <a href="#0">Reglamentos</a>
            </li>
            <li>
              <a href="#0">Decretos</a>
            </li>
            <li>
              <a href="#0">Acuerdos</a>
            </li>
          </ul>
        </div>
      </div>

      <main>
        <div className="content">
          <div className="column-left">
            <TreeComponent nodes={nodes} setShowContent={setShowContent} />
            {/*
            <Tree
              content="Apple"
              type="Fruit"
              open
              canHide
              visible
              onClick={console.log}
            >
              <Tree content="Contents">
                <Tree content="Seeds" />
              </Tree>
            </Tree>
            */}
          </div>
          <div className="column-right">
            {showContent ? (
              <div>
                <strong>Articulo 1</strong>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
                  turpis nisi, ullamcorper id enim id, consequat euismod mauris.
                  Pellentesque eget lacinia erat. In hac habitasse platea
                  dictumst. Phasellus consectetur a nulla vitae lobortis.
                  Vivamus vestibulum ultrices augue vel feugiat. In venenatis
                  purus eget tellus mattis, eget viverra nisi aliquam. Donec et
                  lacus ante. Phasellus hendrerit fringilla erat.
                </p>
                <p>
                  <strong>REFERENCIAS</strong>
                  <ul>
                    <li>
                      <a href="#" style={{ color: "#0000ff" }}>
                        Link 1
                      </a>
                    </li>
                    <li>
                      <a href="#" style={{ color: "#0000ff" }}>
                        Link 2
                      </a>
                    </li>
                  </ul>
                </p>
              </div>
            ) : (
              "Contenido de La Ley"
            )}
          </div>
        </div>
      </main>
    </LayoutStyles>
  );
}

export const getStaticProps = async () => {
  const leyNormasTipos = await axios.get(`${SiteAPI.leyNormas}/type/2`);

  return {
    props: {
      leyNormasTipos: leyNormasTipos.data,
    },
    revalidate: 1,
  };
};
